services:
  postgres:
    image: postgres:14
    container_name: fx_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - fx_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8.2.4-alpine3.22
    container_name: fx_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  wildfly:
    build:
      context: ./docker
      dockerfile: Dockerfile.wildfly
    container_name: fx_wildfly
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  fx_pgdata:
